// Hand-maintained catalog of course/subject names per university, used for the Group course-tag dropdown.
export const courseCatalog: Record<string, string[]> = {
  "Colegiul National Vasile Lucaciu": [
    "Mathematics",
    "Computer Science",
    "Physics",
    "Chemistry",
    "Biology",
    "Romanian Language and Literature",
    "English Language",
    "French Language",
    "History",
    "Geography",
    "Physical Education",
    "Economics",
    "Logic and Argumentation",
    "Social Education",
    "Religion",
  ],
  "No university yet": [],
  "Universitatea din București": [
    "Data Structures and Algorithms",
    "Programming Fundamentals",
    "Object-Oriented Programming",
    "Databases",
    "Real Analysis",
    "Abstract Algebra",
    "Differential Equations",
    "Probability Theory",
    "Topology",
    "Calculus",
    "Linear Algebra",
    "Discrete Mathematics",
    "Classical Mechanics",
    "Electromagnetism",
    "Quantum Mechanics",
    "Thermodynamics and Statistical Physics",
    "Optics",
    "Nuclear Physics",
    "General Chemistry",
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Physical Chemistry",
    "Civil Law",
    "Constitutional Law",
    "Roman Law",
    "Administrative Law",
    "Criminal Law",
    "Romanian Literature",
    "General Linguistics",
    "World Literature",
    "English Language and Literature",
    "French Language and Literature",
    "German Language and Literature",
    "Ancient History",
    "Medieval History of Romania",
    "Modern Universal History",
    "General Psychology",
    "Developmental Psychology",
    "Cognitive Psychology",
    "Educational Psychology",
    "Cell Biology",
    "Botany",
    "Zoology",
    "Genetics",
    "Political Theory",
    "Comparative Politics",
    "International Relations",
    "Introduction to Journalism",
    "Media Studies",
    "Introduction to Sociology",
    "Social Work Fundamentals",
    "Physical Geography",
    "Human Geography",
    "General Geology",
    "Introduction to Philosophy",
    "Ethics",
    "History of Philosophy",
    "Introduction to Theology",
    "Biblical Studies",
    "Theory of Physical Education and Sport",
    "Kinesiology",
  ],
  "Universitatea Babeș-Bolyai din Cluj-Napoca": [
    "Data Structures and Algorithms",
    "Programming Fundamentals",
    "Object-Oriented Programming",
    "Databases",
    "Real Analysis",
    "Abstract Algebra",
    "Differential Equations",
    "Probability Theory",
    "Topology",
    "Calculus",
    "Linear Algebra",
    "Discrete Mathematics",
    "Classical Mechanics",
    "Electromagnetism",
    "Quantum Mechanics",
    "Thermodynamics and Statistical Physics",
    "Optics",
    "Nuclear Physics",
    "General Chemistry",
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Physical Chemistry",
    "Microeconomics",
    "Macroeconomics",
    "Financial Accounting",
    "Business Statistics",
    "Marketing Principles",
    "Corporate Finance",
    "Business Administration",
    "Civil Law",
    "Constitutional Law",
    "Roman Law",
    "Criminal Law",
    "Romanian Literature",
    "General Linguistics",
    "Comparative Literature",
    "Cell Biology",
    "General Geology",
    "Botany",
    "Zoology",
    "Environmental Science",
    "General Psychology",
    "Developmental Psychology",
    "Cognitive Psychology",
    "Introduction to Political Science",
    "Public Communication",
    "European Studies",
    "European Union Law",
    "Physical Geography",
    "Human Geography",
    "Introduction to Theology",
    "History of Theatre",
    "Film Studies",
    "History",
    "Introduction to Philosophy",
    "Introduction to Sociology",
    "Social Work Fundamentals",
    "Theory of Physical Education and Sport",
    "Sports Medicine",
    "Human Anatomy",
    "Physiology",
  ],
  "Universitatea Politehnica din București": [
    "Data Structures and Algorithms",
    "Programming Fundamentals",
    "Digital Logic Design",
    "Operating Systems",
    "Computer Architecture",
    "Calculus",
    "Linear Algebra",
    "Differential Equations",
    "Electrical Circuits",
    "Signals and Systems",
    "Electronics Fundamentals",
    "Telecommunications Fundamentals",
    "Thermodynamics",
    "Power Systems Engineering",
    "Electrical Machines",
    "Renewable Energy Systems",
    "Aerodynamics",
    "Flight Mechanics",
    "Aircraft Structures",
    "Mechanics of Materials",
    "Machine Design",
    "Mechatronics",
    "Robotics Fundamentals",
    "Industrial Engineering",
    "Manufacturing Processes",
    "Transport Systems Engineering",
    "Engineering Materials Science",
    "Technical Drawing and CAD",
    "Automatic Control Systems",
    "Applied Physics",
    "Biomedical Engineering Fundamentals",
    "Medical Instrumentation",
    "Biotechnical Systems Engineering",
    "Engineering Management",
    "Entrepreneurship Fundamentals",
    "Chemical Engineering Fundamentals",
  ],
  "Universitatea de Vest din Timișoara": [
    "Data Structures and Algorithms",
    "Programming Fundamentals",
    "Databases",
    "Real Analysis",
    "Abstract Algebra",
    "Differential Equations",
    "Probability Theory",
    "Calculus",
    "Linear Algebra",
    "Classical Mechanics",
    "Electromagnetism",
    "Thermodynamics and Statistical Physics",
    "Optics",
    "Microeconomics",
    "Macroeconomics",
    "Financial Accounting",
    "Marketing Principles",
    "Business Administration",
    "Civil Law",
    "Constitutional Law",
    "Administrative Law",
    "Romanian Literature",
    "Universal History",
    "History of Romania",
    "General Chemistry",
    "Organic Chemistry",
    "Cell Biology",
    "Botany",
    "Physical Geography",
    "Introduction to Philosophy",
    "Ethics",
    "Political Theory",
    "Public Communication",
    "Introduction to Sociology",
    "Social Work Fundamentals",
    "General Psychology",
    "Educational Psychology",
    "Introduction to Theology",
    "History of Art",
    "Music Theory",
    "Theory of Physical Education and Sport",
    "Kinesiology",
    "Sports Medicine",
    "Coaching Methodology",
  ],
  "Academia de Studii Economice din București": [
    "Microeconomics",
    "Macroeconomics",
    "Financial Accounting",
    "Management Accounting",
    "Business Statistics",
    "Corporate Finance",
    "Marketing Principles",
    "Management Fundamentals",
    "International Trade",
    "International Economic Relations",
    "Money and Banking",
    "Insurance and Financial Markets",
    "Economic Cybernetics",
    "Business Law",
    "Public Administration",
    "Public Management",
    "Econometrics",
    "Business Informatics",
    "Economic Informatics Systems",
    "Human Resource Management",
    "Business Administration",
    "Tourism Economics",
    "Agri-food Economics",
    "Environmental Economics",
    "Theoretical Economics",
    "Applied Economics",
  ],
  "Universitatea de Științe Agricole și Medicină Veterinară din Cluj-Napoca": [
    "Agronomy",
    "Soil Science",
    "Plant Physiology",
    "Phytopathology",
    "Agricultural Machinery",
    "Viticulture",
    "Pomology",
    "Vegetable Growing",
    "Landscape Architecture Fundamentals",
    "Animal Husbandry",
    "Animal Nutrition",
    "Animal Breeding and Genetics",
    "Veterinary Anatomy",
    "Veterinary Physiology",
    "Animal Pathology",
    "Veterinary Microbiology",
    "Veterinary Pharmacology",
    "Parasitology",
    "Food Technology",
    "Food Chemistry",
    "Food Safety and Quality Control",
    "Forest Management",
    "Dendrology",
    "Cadastre and Land Measurements",
    "Biochemistry",
    "Genetics",
    "Biotechnology Fundamentals",
  ],
  "Universitatea de Medicină și Farmacie Iuliu Hațieganu din Cluj-Napoca": [
    "Human Anatomy",
    "Physiology",
    "Biochemistry",
    "Histology",
    "Embryology",
    "Pathophysiology",
    "Pathological Anatomy",
    "Internal Medicine",
    "Surgery",
    "Pediatrics",
    "Pharmacology",
    "Microbiology",
    "Public Health and Management",
    "Epidemiology",
    "Medical Ethics",
    "Dental Anatomy",
    "Oral Pathology",
    "Dental Materials Science",
    "Prosthodontics",
    "Orthodontics",
    "Oral Surgery",
    "Pharmaceutical Chemistry",
    "Pharmacognosy",
    "Pharmaceutical Technology",
    "Toxicology",
    "Pharmaceutical Botany",
    "Fundamentals of Nursing",
    "Clinical Nursing",
    "Medical Genetics",
    "Immunology",
    "Cell Biology",
    "Radiology and Medical Imaging",
  ],
  "Universitatea Ovidius din Constanța": [
    "Human Anatomy",
    "Physiology",
    "Biochemistry",
    "Internal Medicine",
    "Pharmacology",
    "Public Health",
    "Dental Anatomy",
    "Prosthodontics",
    "Pharmaceutical Chemistry",
    "Pharmaceutical Technology",
    "Civil Law",
    "Constitutional Law",
    "Administrative Law",
    "Microeconomics",
    "Macroeconomics",
    "Financial Accounting",
    "Business Administration",
    "Marketing Principles",
    "Data Structures and Algorithms",
    "Programming Fundamentals",
    "Calculus",
    "Linear Algebra",
    "Romanian Literature",
    "Universal History",
    "Cell Biology",
    "Botany",
    "General Chemistry",
    "Ancient History",
    "Political Theory",
    "Introduction to Theology",
    "Mechanics of Materials",
    "Naval Architecture Fundamentals",
    "Marine Engineering",
    "Industrial Engineering",
    "Physical Geography",
    "Human Geography",
    "Theory of Physical Education and Sport",
    "Kinesiology",
  ],
  "Universitatea Alexandru Ioan Cuza din Iași": [
    "Data Structures and Algorithms",
    "Programming Fundamentals",
    "Object-Oriented Programming",
    "Databases",
    "Real Analysis",
    "Abstract Algebra",
    "Differential Equations",
    "Probability Theory",
    "Discrete Mathematics",
    "Calculus",
    "Linear Algebra",
    "Classical Mechanics",
    "Electromagnetism",
    "Thermodynamics and Statistical Physics",
    "Optics",
    "General Chemistry",
    "Organic Chemistry",
    "Microeconomics",
    "Macroeconomics",
    "Financial Accounting",
    "Marketing Principles",
    "Business Administration",
    "Civil Law",
    "Constitutional Law",
    "Romanian Literature",
    "General Linguistics",
    "Cell Biology",
    "Botany",
    "General Psychology",
    "Developmental Psychology",
    "Educational Psychology",
    "Ancient History",
    "Medieval History of Romania",
    "Introduction to Philosophy",
    "Ethics",
    "Political Theory",
    "Introduction to Sociology",
    "Physical Geography",
    "General Geology",
    "Introduction to Theology",
    "Biblical Studies",
    "Theory of Physical Education and Sport",
    "Kinesiology",
    "Sports Medicine",
  ],
  "Universitatea de Medicină și Farmacie Carol Davila din București": [
    "Human Anatomy",
    "Physiology",
    "Biochemistry",
    "Histology",
    "Embryology",
    "Pathophysiology",
    "Pathological Anatomy",
    "Internal Medicine",
    "Surgery",
    "Pediatrics",
    "Pharmacology",
    "Microbiology",
    "Public Health",
    "Epidemiology",
    "Medical Ethics",
    "Medical Genetics",
    "Dental Anatomy",
    "Oral Pathology",
    "Dental Materials Science",
    "Prosthodontics",
    "Orthodontics",
    "Oral Surgery",
    "Pharmaceutical Chemistry",
    "Pharmacognosy",
    "Pharmaceutical Technology",
    "Toxicology",
    "Pharmaceutical Botany",
    "Fundamentals of Nursing",
    "Obstetrics and Midwifery Care",
    "Clinical Nursing",
    "Radiology and Medical Imaging",
    "Physiotherapy Fundamentals",
    "Immunology",
    "Cell Biology",
  ],
  "Universitatea Politehnica Timișoara": [
    "Data Structures and Algorithms",
    "Programming Fundamentals",
    "Digital Logic Design",
    "Operating Systems",
    "Structural Mechanics",
    "Reinforced Concrete Structures",
    "Building Materials",
    "Geotechnical Engineering",
    "Architectural Design Studio",
    "History of Architecture",
    "Urban Planning Fundamentals",
    "Electrical Circuits",
    "Electronics Fundamentals",
    "Signals and Systems",
    "Telecommunications Fundamentals",
    "Chemical Process Engineering",
    "Biotechnology Fundamentals",
    "Environmental Engineering",
    "Power Systems Engineering",
    "Electrical Machines",
    "Renewable Energy Systems",
    "Mechanics of Materials",
    "Machine Design",
    "Manufacturing Processes",
    "Engineering Management",
    "Transport and Logistics Management",
    "Technical Drawing and CAD",
    "Communication Sciences Fundamentals",
    "Calculus",
    "Linear Algebra",
  ],
  "Universitatea Transilvania din Brașov": [
    "Data Structures and Algorithms",
    "Programming Fundamentals",
    "Digital Logic Design",
    "Mechanics of Materials",
    "Machine Design",
    "Thermodynamics",
    "Manufacturing Processes",
    "Electrical Circuits",
    "Signals and Systems",
    "Electronics Fundamentals",
    "Structural Mechanics",
    "Reinforced Concrete Structures",
    "Building Materials",
    "Human Anatomy",
    "Physiology",
    "Pharmacology",
    "Romanian Literature",
    "General Linguistics",
    "Microeconomics",
    "Macroeconomics",
    "Financial Accounting",
    "Marketing Principles",
    "Business Administration",
    "Engineering Materials Science",
    "Forest Management",
    "Dendrology",
    "Wood Processing Technology",
    "Civil Law",
    "Constitutional Law",
    "Industrial Design Fundamentals",
    "Product Design Fundamentals",
    "Food Technology",
    "Tourism Management",
    "Music Theory",
    "Introduction to Sociology",
    "Social Work Fundamentals",
    "General Psychology",
    "Educational Psychology",
    "Theory of Physical Education and Sport",
    "Kinesiology",
  ],
};
