export const universityDomains: Record<string, string> = {
  "lucaciu.ro": "Colegiul National Vasile Lucaciu",
  "gmail.com": "No university yet",
  "unibuc.ro": "Universitatea din București",
  "ubbcluj.ro": "Universitatea Babeș-Bolyai din Cluj-Napoca",
  "upb.ro": "Universitatea Politehnica din București",
  "uvt.ro": "Universitatea de Vest din Timișoara",
  "ase.ro": "Academia de Studii Economice din București",
  "usamvcluj.ro": "Universitatea de Științe Agricole și Medicină Veterinară din Cluj-Napoca",
  "umft.ro": "Universitatea de Medicină și Farmacie Iuliu Hațieganu din Cluj-Napoca",
  "ubb.ro": "Universitatea Babeș-Bolyai din Cluj-Napoca",
  "univ-ovidius.ro": "Universitatea Ovidius din Constanța",
  "e-uvt.ro": "Universitatea de Vest din Timișoara",
  "uaic.ro": "Universitatea Alexandru Ioan Cuza din Iași",
  "umfcd.ro": "Universitatea de Medicină și Farmacie Carol Davila din București",
  "upt.ro": "Universitatea Politehnica Timișoara",
  "unitbv.ro": "Universitatea Transilvania din Brașov",
  "stud.ubbcluj.ro": "Universitatea Babeș-Bolyai din Cluj-Napoca",
};
