export const universityEmailDomains: string[] = [
  "lucaciu.ro",
  "gmail.com",
  "unibuc.ro",
  "ubbcluj.ro",
  "upb.ro",
  "e-uvt.ro",
  "uvt.ro",
  "uaic.ro",
  "umfcd.ro",
  "upt.ro",
  "utcn.ro",
  "unitbv.ro",
  "stud.ubbcluj.ro",
];
