import LegalPageLayout from "./LegalPageLayout";

const PrivacyPolicy = () => {
  return (
    <LegalPageLayout title="Privacy Policy" lastUpdated="August 26, 2026">
      <section className="flex flex-col gap-3">
        <p>
          This Privacy Policy explains what information Universe collects
          when you use the app, why we collect it, and the scope in which
          it's stored and shared. Universe is a student-focused social
          platform, so most of what we collect is the information you
          choose to share by creating an account and using the app's
          features.
        </p>
      </section>

      <section className="flex flex-col gap-3">
        <h2>Account &amp; profile information</h2>
        <p>Scope: stored on your account, visible per your profile/privacy settings.</p>
        <ul>
          <li>Name, username, and university email address used to sign up and log in</li>
          <li>Password, stored only as a salted hash — we never store or can see your plaintext password</li>
          <li>University and major, if you add them to your profile</li>
          <li>Bio and profile picture, if you set them</li>
          <li>Account type (student or university/organization account) and, for organization accounts, verification/review status</li>
          <li>If you sign up or log in with Google, the Google account identifier used to link your account</li>
        </ul>
      </section>

      <section className="flex flex-col gap-3">
        <h2>Authentication &amp; security data</h2>
        <p>Scope: internal use only, never shown to other users.</p>
        <ul>
          <li>Email verification codes and password-reset tokens, used only to confirm it's really you</li>
          <li>Session/refresh tokens that keep you signed in</li>
          <li>Login timestamps, used to secure your account and show your last-active status where applicable</li>
        </ul>
      </section>

      <section className="flex flex-col gap-3">
        <h2>Content you create</h2>
        <p>Scope: visible to other users according to the audience you post to (public, followers, group, or a direct conversation).</p>
        <ul>
          <li>Posts, comments, likes, saved posts, and tags you use</li>
          <li>Direct messages and group messages, including text, images, and audio attachments you send</li>
          <li>Polls you create and the votes you cast</li>
          <li>Events you create or RSVP to, including event location and any virtual meeting link you add</li>
        </ul>
      </section>

      <section className="flex flex-col gap-3">
        <h2>Your connections &amp; activity</h2>
        <p>Scope: used to power the social features you opt into.</p>
        <ul>
          <li>Who you follow and who follows you</li>
          <li>Groups you belong to, and group membership/ban records where applicable</li>
          <li>Accounts you block, which we use to stop that account from interacting with you across the app</li>
          <li>Notifications generated by your activity (likes, comments, follows, mentions, messages, event updates)</li>
        </ul>
      </section>

      <section className="flex flex-col gap-3">
        <h2>App preferences</h2>
        <p>Scope: stored on your account so your settings persist across devices.</p>
        <ul>
          <li>Theme (light/dark) and notification preferences</li>
        </ul>
      </section>

      <section className="flex flex-col gap-3">
        <h2>How we use this information</h2>
        <p>
          We use your information to operate and secure Universe: to
          authenticate you, display your profile and content to the right
          audience, power search, deliver notifications, and enforce
          blocks and bans you or moderators put in place. We do not sell
          your personal data.
        </p>
      </section>

      <section className="flex flex-col gap-3">
        <h2>Who can see your information</h2>
        <p>
          Your profile and public posts are visible to other Universe
          users (and, for posts you share publicly, anyone with the link).
          Direct messages and group messages are visible only to the
          participants of that conversation or group. Blocked accounts are
          prevented from viewing your content or contacting you.
        </p>
      </section>

      <section className="flex flex-col gap-3">
        <h2>Your choices</h2>
        <ul>
          <li>Edit or remove profile information at any time from your account settings</li>
          <li>Delete posts, comments, and messages you've created</li>
          <li>Block accounts you don't want interacting with you</li>
          <li>Control notification preferences from Settings</li>
          <li>Request deletion of your account and associated data by contacting us</li>
        </ul>
      </section>

      <section className="flex flex-col gap-3">
        <h2>Contact</h2>
        <p>
          If you have questions about this Privacy Policy or how your data
          is handled, reach out to the Universe team through the app's
          support channels.
        </p>
      </section>
    </LegalPageLayout>
  );
};

export default PrivacyPolicy;
