import LegalScreenLayout, { type LegalSectionData } from "@components/settings/LegalScreenLayout";

const SECTIONS: LegalSectionData[] = [
  {
    blocks: [
      {
        type: "paragraph",
        text: "This Privacy Policy explains what information Universe collects when you use the app, why we collect it, and the scope in which it's stored and shared. Universe is a student-focused social platform, so most of what we collect is the information you choose to share by creating an account and using the app's features.",
      },
    ],
  },
  {
    heading: "Account & profile information",
    blocks: [
      { type: "paragraph", text: "Scope: stored on your account, visible per your profile/privacy settings." },
      {
        type: "list",
        items: [
          "Name, username, and university email address used to sign up and log in",
          "Password, stored only as a salted hash — we never store or can see your plaintext password",
          "University and major, if you add them to your profile",
          "Bio and profile picture, if you set them",
          "Account type (student or university/organization account) and, for organization accounts, verification/review status",
          "If you sign up or log in with Google, the Google account identifier used to link your account",
        ],
      },
    ],
  },
  {
    heading: "Authentication & security data",
    blocks: [
      { type: "paragraph", text: "Scope: internal use only, never shown to other users." },
      {
        type: "list",
        items: [
          "Email verification codes and password-reset tokens, used only to confirm it's really you",
          "Session/refresh tokens that keep you signed in",
          "Login timestamps, used to secure your account and show your last-active status where applicable",
        ],
      },
    ],
  },
  {
    heading: "Content you create",
    blocks: [
      {
        type: "paragraph",
        text: "Scope: visible to other users according to the audience you post to (public, followers, group, or a direct conversation).",
      },
      {
        type: "list",
        items: [
          "Posts, comments, likes, saved posts, and tags you use",
          "Direct messages and group messages, including text, images, and audio attachments you send",
          "Polls you create and the votes you cast",
          "Events you create or RSVP to, including event location and any virtual meeting link you add",
        ],
      },
    ],
  },
  {
    heading: "Your connections & activity",
    blocks: [
      { type: "paragraph", text: "Scope: used to power the social features you opt into." },
      {
        type: "list",
        items: [
          "Who you follow and who follows you",
          "Groups you belong to, and group membership/ban records where applicable",
          "Accounts you block, which we use to stop that account from interacting with you across the app",
          "Notifications generated by your activity (likes, comments, follows, mentions, messages, event updates)",
        ],
      },
    ],
  },
  {
    heading: "App preferences",
    blocks: [
      { type: "paragraph", text: "Scope: stored on your account so your settings persist across devices." },
      { type: "list", items: ["Theme (light/dark) and notification preferences"] },
    ],
  },
  {
    heading: "How we use this information",
    blocks: [
      {
        type: "paragraph",
        text: "We use your information to operate and secure Universe: to authenticate you, display your profile and content to the right audience, power search, deliver notifications, and enforce blocks and bans you or moderators put in place. We do not sell your personal data.",
      },
    ],
  },
  {
    heading: "Who can see your information",
    blocks: [
      {
        type: "paragraph",
        text: "Your profile and public posts are visible to other Universe users (and, for posts you share publicly, anyone with the link). Direct messages and group messages are visible only to the participants of that conversation or group. Blocked accounts are prevented from viewing your content or contacting you.",
      },
    ],
  },
  {
    heading: "Your choices",
    blocks: [
      {
        type: "list",
        items: [
          "Edit or remove profile information at any time from your account settings",
          "Delete posts, comments, and messages you've created",
          "Block accounts you don't want interacting with you",
          "Control notification preferences from Settings",
          "Request deletion of your account and associated data by contacting us",
        ],
      },
    ],
  },
  {
    heading: "Contact",
    blocks: [
      {
        type: "paragraph",
        text: "If you have questions about this Privacy Policy or how your data is handled, reach out to the Universe team through the app's support channels.",
      },
    ],
  },
];

const PrivacyPolicy = () => (
  <LegalScreenLayout title="Privacy Policy" lastUpdated="August 26, 2026" sections={SECTIONS} />
);

export default PrivacyPolicy;
